/*
Vapor Test Suite
2005: Try catch finally

- output
Hello exception world.
Finally executed.
*/

using Core;

class MyException: Exception
{
	public String message;

	public (String message)
	{
		this.message = message;
	}
}

class Test
{
	public static Main()
	{
		try
		{
			throw new MyException("Hello exception world.");
		}
		catch (MyException e)
		{
			Console.WriteLine(e.message);
		}
		finally
		{
			Console.WriteLine("Finally executed.");
		}
	}
}
