/*
Vapor Test Suite
2005: Try catch finally

- output
Hello exception world.
Finally executed.
*/

class MyException: Core.Exception
{
	public Core.String message;

	public function .ctor(Core.String message)
	{
		this::message = message;
	}
}

class Test
{
	public static function Main()
	{
		try
		{
			throw new MyException("Hello exception world.");
		}
		catch (MyException e)
		{
			Core.Console::WriteLine(e::message);
		}
		finally
		{
			Core.Console::WriteLine("Finally executed.");
		}
	}
}
