/*
Vapor Test Suite
2011: Return values in try finally block

- output
Finally 0 executed.
Finally 1 executed.
This is the value!
Finally 2 executed.
The answer is 42
*/

using Core;

class MyException: Exception
{
	public String message;

	public (String message)
	{
		this.message = message;
	}
}

class Test
{
	public static Func0()
	{
		try
			for (int32 i = 0; i < 100000000; i = i + 1)
				return;
		finally
			Console.WriteLine("Finally 0 executed.");
	}
	public static Func1() -> String
	{
		try
			return "This is the value!";
		finally
			Console.WriteLine("Finally 1 executed.");
	}

	public static Func2() -> String, int32
	{
		try
			return "The answer is ", 42;
		finally
			Console.WriteLine("Finally 2 executed.");
	}

	public static Main()
	{
		Func0();
		Console.WriteLine(Func1());
		String str;
		int32 i;
		str, i = Func2();
		Console.WriteLine(str + Int32.ToString(i));
	}
}
